[package]
name = "drp-common"
description = "Shared types, errors, IDs, and utilities for the Data Reliability Platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
config.workspace = true
indexmap.workspace = true
serde = { workspace = true }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
ulid.workspace = true
uuid.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
